# Lychee link checker configuration
# Treat 429s (rate limited) as warnings and retry; ignore localhost/file links
max_concurrency = 5
scheme = ["http", "https"]
accept = ["200..299", "403", "429"]
retry_wait_time = 2
max_retries = 2

# Exclusions: private networks, anchors known to be flaky
exclude = [
  "^http://localhost",
  "^https://localhost",
  "^http://127\\.0\\.0\\.1",
  "^https://127\\.0\\.0\\.1",
  "^file://",
]
