name: CI (docs: lint + links)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          # Respect .markdownlint.json; lint all Markdown files
          globs: |
            **/*.md
            !**/node_modules/**
            !**/.git/**

  links:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links in Markdown
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --no-progress
            --config .lychee.toml
            --max-concurrency 5
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
